# HW1 - Covariance Matrix

**Covariance** is used to measure how two random variables change or vary together. For example, the height and weight of giraffes have a positive covariance because when one is big, the other tends to also be big.

_In this assignment, we will calculate the **covariance matrix** for a given dataset._

This assignment will consist of two parts:

## Part 1

**IMPORTANT NOTE:** in the video, the equation he uses has $n$ as the denominator, but when he calculates covariance values, he's using $n-1$ as the denominator. _For our purposes, we will be using $n-1$ as the denominator._

Watch this video on covariance matrices: https://www.youtube.com/watch?v=0GzMcUy7ZI0

Mathematically, we can represent Covariance as such:

$Cov(X,Y)=1/(n-1) \sum_{i=1}^{n}(x[i] - \bar{x})(y[i] - \bar{y})$

Where $n$ is the number of elements in arrays $x$ and $y$

## Part 2

Write a Python function that returns the covariance matrix for a given dataset, just like we watched in the video or any other dataset of your choosing. Below are various places you can get datasets from:

### Dataset Resources

- [Kaggle](https://www.kaggle.com/datasets)
- [Fivethirtyeight](https://github.com/fivethirtyeight/data)
- [Buzzfeed News](https://github.com/BuzzFeedNews/everything)
- [Google Cloud BigQuery Public Datasets](https://cloud.google.com/bigquery/public-data/)
- [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Database_download)
- Can't find anything from above? Google around until you do!

## Part 3

Use [numpy's var function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html) to confirm that the covariance between a variable and itself is the same as the variance of the variable.

For example, assuming your covariance function is named `cov`, ensure that the following is true: `cov(X, X) == np.var(X)`

### Hints

1. Obtain the covariance between columns $x$ and $y$, between columns $x$ and $z$, and columns $y$ and $z$
1. The covariance between columns $x$ and $y$ is the same as the covariance between columns $y$ and $x$. _We can generalize this for any two columns_
1. Show that the covariance between columns $x$ and $x$ is equal to the variance of column $x$. _We can generalize this for any other column_

## Testing Your Code

Verify your code with numpy built-in `np.cov()` function as follows:

In [3]:
import numpy as np

def cov_matrix_calculation(data):
    # calculate covariance matrix of the data
    cov_matx = np.cov(data.T)
    return cov_matx

dataset = np.array([[1, 1, 1], [1, 2, 1], [1, 3, 2], [1, 4, 3]])
print(cov_matrix_calculation(dataset))

[[0.         0.         0.        ]
 [0.         1.66666667 1.16666667]
 [0.         1.16666667 0.91666667]]


# Requirements

To pass this HW, you must meet the following requirements

1. Your function should return the covariance between 6 pairs of random variables: $(X,Y), (X, Z), (Y, Z), (X, X), (Y, Y), and (Z, Z)$
1. Verify that your function's return value is correct by using `np.cov(DATA)` where `DATA` is the return value of your covariance function
1. Verify that your covariance function for each variable with itself returns the same value as `np.var` of that variable

## Stretch Challenges

These are optional challenges for those who want to further expand their skillset:

1. Your function should display the covariance in a matrix format

## Turning In Your HW

Once you have finished your assignment, provide a link to your repo on GitHub and place the link in the appropriate `HW1` column in the progress tracker. See the syllabus for more details on submission links

In [7]:
import numpy as np
import pandas as pd

df = pd.read_csv('../../drug-use-by-age.csv')
# print(df['age'])

# keep getting error that file is not found. I manually input the data.
# the 4 subjects are the ages: 12, 13, 14, 15
# x = alcohol use, y = marijuana use, z = cocaine use


def cov_matrix_calculation(data):
    cov_matrix = np.cov(data.T)
    cov_matrix_rounded = np.around(cov_matrix, decimals = 1)
    
    return cov_matrix_rounded

twelve_yr_old = [3.9, 1.1, 0.1]
thirteen_yr_old = [8.5, 3.4, 0.1]
fourteen_yr_old = [18.1, 8.7, 0.1]
fifteen_yr_old = [29.2, 14.5, 0.5]

x = [3.9, 8.5, 18.1, 29.2]
y = [1.1, 3.4, 8.7, 14.5]
z = [0.1, 0.1, 0.1, 0.5]

x_mean = np.mean(x) # expected 14.925
# print(x_mean)

def calc_variance(ls):
    mean_ls = np.mean(ls)
    sum_squared_from_mean = sum([(i - mean_ls)**2 for i in ls])
    return sum_squared_from_mean/(len(ls) - 1)



print("Variance of the x column: " + str(calc_variance([3.9, 8.5, 18.1, 29.2]))) # this is variance for the x column. Expected value = 125.6

x_var = np.var(x, ddof=1)
print("Expected variance of x is: " + str(x_var) + "\n") # double check that the function calc_variance is correct with np.var(), it is correct


print("Variance of the y column: " + str(calc_variance([1.1, 3.4, 8.7, 14.5]))) # this is the variance for the y column. Expected value = 35.6
print("Variance of the z column: " + str(calc_variance([0.1, 0.1, 0.1, 0.5]))) # this is the variance for the z column. Expected value = 0.0


dataset_one = np.array([[3.9, 1.1, 0.1], [8.5, 3.4, 0.1], [18.1, 8.7, 0.1], [29.2, 14.5, 0.5]])

print("Matrix of data: \n" + str(dataset_one) + "\n")
print("Covariance: \n" + str(cov_matrix_calculation(dataset_one)) + "\n")

# print("This is the x column: " + str(x_column)) # prints out the x column 

print("This is cov(x,x): " + str(cov_matrix_calculation(dataset_one)[0,0])) # prints out cov(x, x)
print("This is cov(y,y): " + str(cov_matrix_calculation(dataset_one)[1,1])) # prints out cov(y,y)
print("This is cov(z,z): " + str(cov_matrix_calculation(dataset_one)[2,2])) #prints out cov(z,z)

Variance of the x column: 125.5625
Expected variance of x is: 125.5625

Variance of the y column: 35.62916666666666
Variance of the z column: 0.04
Matrix of data: 
[[ 3.9  1.1  0.1]
 [ 8.5  3.4  0.1]
 [18.1  8.7  0.1]
 [29.2 14.5  0.5]]

Covariance: 
[[125.6  66.9   1.9]
 [ 66.9  35.6   1. ]
 [  1.9   1.    0. ]]

This is cov(x,x): 125.6
This is cov(y,y): 35.6
This is cov(z,z): 0.0


In [6]:
df.head()

age     n  alcohol-use  alcohol-frequency  marijuana-use  \
0  12  2798          3.9                3.0            1.1   
1  13  2757          8.5                6.0            3.4   
2  14  2792         18.1                5.0            8.7   
3  15  2956         29.2                6.0           14.5   
4  16  3058         40.1               10.0           22.5   

   marijuana-frequency  cocaine-use cocaine-frequency  crack-use  \
0                  4.0          0.1               5.0        0.0   
1                 15.0          0.1               1.0        0.0   
2                 24.0          0.1               5.5        0.0   
3                 25.0          0.5               4.0        0.1   
4                 30.0          1.0               7.0        0.0   

  crack-frequency  ...  oxycontin-use oxycontin-frequency  tranquilizer-use  \
0               -  ...            0.1                24.5               0.2   
1             3.0  ...            0.1                41.0               0.3   
2               -  ...            0.4                 4.5               0.9   
3             9.5  ...            0.8                 3.0               2.0   
4             1.0  ...            1.1                 4.0               2.4   

   tranquilizer-frequency  stimulant-use stimulant-frequency  meth-use  \
0                    52.0            0.2                 2.0       0.0   
1                    25.5            0.3                 4.0       0.1   
2                     5.0            0.8                12.0       0.1   
3                     4.5            1.5                 6.0       0.3   
4                    11.0            1.8                 9.5       0.3   

   meth-frequency  sedative-use sedative-frequency  
0               -           0.2               13.0  
1             5.0           0.1               19.0  
2            24.0           0.2               16.5  
3            10.5           0.4               30.0  
4            36.0           0.2                3.0  

[5 rows x 28 columns]

In [5]:
twelve_yr_old = [3.9, 1.1, 0.1]
thirteen_yr_old = [8.5, 3.4, 0.1]
fourteen_yr_old = [18.1, 8.7, 0.1]
fifteen_yr_old = [29.2, 14.5, 0.5]

x = [3.9, 8.5, 18.1, 29.2]
y = [1.1, 3.4, 8.7, 14.5]
z = [0.1, 0.1, 0.1, 0.5]

x_mean = np.mean(x) # expected 14.925
# print(x_mean)
x_var = np.var(x, ddof=1) # expected value = 125.625

